weights: runs/train/0127memryx_mafa-yolov7-tiny_body_only_s192_3204/weights/epoch_029.pt
cfg: cfg/training/yolov7-tiny.yaml
data: data/0127memryx_MAFA_body_only.yaml
hyp: data/hyp.scratch.p5.ota0.yaml
epochs: 270
batch_size: 128
img_size:
- 192
- 320
rect: false
resume: false
nosave: false
notest: true
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: 4,5,6,7
multi_scale: false
single_cls: false
adam: false
sync_bn: true
local_rank: 0
workers: 8
project: runs/train
entity: null
name: 0127memryx_mafa-yolov7-tiny_body_only_s192_320
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
freeze:
- 0
v5_metric: false
close_mosaic: 0
world_size: 4
global_rank: 0
save_dir: runs/train/0127memryx_mafa-yolov7-tiny_body_only_s192_3206
total_batch_size: 512
